Repository FANMIX-Works/FANMIX-FE, pull requests merged in 2024-09, with the labels that each got.

#3 📦 Chore/#2 브랜치 생성/전환/삭제 명령어 만들기
  .eslintrc.json
  README.md
  git-tools/branch-config.js
  git-tools/commit-config.js
  git-tools/constant.js
  git-tools/push-config.js
  git-tools/util.js
  package.json
  scripts/commitizen.sh
  scripts/update_permissions.sh
  yarn.lock
Labels: 📦 chore

#6 📦 Chore/#5 .eslintrc.json prettier 수정 및 gitattributes 파일 추가
  .eslintrc.json
  .gitattributes
Labels: 📦 chore

#8 📦-Chore/#7-Vercel-자동-배포-설정
  .github/workflows/deploy.yml
  build.sh
Labels: 📦 chore

#10 📦-Chore/#9-DeepSource-세팅
  .deepsource.toml
Labels: 📦 chore

#16 ✨ Feat/#4 next intl 다국어 세팅
  .eslintrc.json
  .vscode/settings.json
  global.d.ts
  messages/en.json
  messages/ko.json
  next.config.mjs
  package.json
  src/app/[locale]/layout.tsx
  src/app/[locale]/page.tsx
  src/app/page.tsx
  src/i18n/request.ts
  src/i18n/routing.ts
  src/middleware.ts
  yarn.lock
Labels: ✨ feat

#20 ✨ Feat/#18 헤더/네비게이션 기본 동작 및 라우팅, 토스트/모달 기능 추가
  messages/en.json
  messages/ko.json
  src/app/[locale]/(auth)/login/page.tsx
  src/app/[locale]/(main)/fan-channel/page.tsx
  src/app/[locale]/(main)/follow/page.tsx
  src/app/[locale]/(main)/layout.tsx
  src/app/[locale]/(main)/my/page.tsx
  src/app/[locale]/(main)/page.tsx
  src/app/[locale]/layout.tsx
  src/app/[locale]/page.tsx
  src/app/globals.css
  src/components/features/expandableMenu/ExpandableMenu.tsx
  src/components/features/mainSearch/MainSearch.tsx
  src/components/layout/BottomNavigation.tsx
  src/components/layout/Header.tsx
  src/components/layout/ModalPortal.tsx
  src/components/layout/ResponsiveLayout.tsx
  src/components/ui/toast.tsx
  src/constants/routes.ts
  src/hooks/useCurrentRouteLabel.tsx
  src/stores/modalStore.ts
  tailwind.config.ts
Labels: ✨ feat

#24 ✨ Feat/#19 하단 네비게이션 스크롤 동작 추가
  package-lock.json
  package.json
  src/app/[locale]/(auth)/login/page.tsx
  src/app/[locale]/(main)/page.tsx
  src/components/layout/BottomNavigation.tsx
  src/components/layout/Header.tsx
  src/components/layout/hooks/useBottomNavigationState.tsx
  src/components/ui/toast.tsx
  src/constants/domIdentifiers.ts
  src/hooks/useScrollDirection.tsx
  tailwind.config.ts
  yarn.lock
Labels: ✨ feat

#26 ✨ Feat/#22 마이페이지 스크린 작업, 네비게이션 스크롤 오류 수정
  messages/en.json
  messages/ko.json
  package.json
  src/app/[locale]/(auth)/login/page.tsx
  src/app/[locale]/(main)/fan-channel/page.tsx
  src/app/[locale]/(main)/follow/page.tsx
  src/app/[locale]/(main)/my/edit/page.tsx
  src/app/[locale]/(main)/my/page.tsx
  src/app/[locale]/(main)/page.tsx
  src/components/common/BadgeList.tsx
  src/components/features/header/alarm/MainAlarm.tsx
  src/components/features/header/expandableMenu/ExpandableMenu.tsx
  src/components/features/header/index.ts
  src/components/features/header/search/MainSearch.tsx
  src/components/features/influencer/index.ts
  src/components/features/influencer/onePick/OnePickInfluencer.tsx
  src/components/features/user/avatar/UserAvatar.tsx
  src/components/features/user/hooks/useUserProfileImage.tsx
  src/components/features/user/index.ts
  src/components/features/user/profile/MyProfile.tsx
  src/components/layout/BottomNavigation.tsx
  src/components/layout/Header.tsx
  src/components/layout/hooks/useBottomNavigationState.tsx
  src/components/ui/avatar.tsx
  src/components/ui/badge.tsx
  src/components/ui/button.tsx
  src/components/ui/separator.tsx
  src/components/ui/switch.tsx
  src/constants/routes.ts
  src/hooks/useCurrentRouteLabel.tsx
  src/hooks/useGoBack.tsx
  src/hooks/useScrollDirection.tsx
  tailwind.config.ts
  yarn.lock
Labels: 🐛 fix, ✨ feat

#27 🛠️ Refactor/#25 페이지 별 레이아웃에 타이틀 설정, 폴더 구조 수정
  messages/en.json
  messages/ko.json
  src/app/[locale]/(auth)/login/page.tsx
  src/app/[locale]/(main)/fan-channel/page.tsx
  src/app/[locale]/(main)/follow/page.tsx
  src/app/[locale]/(main)/my/edit/page.tsx
  src/app/[locale]/(main)/my/page.tsx
  src/app/[locale]/(main)/page.tsx
  src/app/[locale]/layout.tsx
  src/app/globals.css
  src/components/common/badge/BadgeList.tsx
  src/components/common/button/GoBackButton.tsx
  src/components/common/carousel/IntroImageCarousel.tsx
  src/components/domain/auth/DeleteAccountButton.tsx
  src/components/domain/auth/GoogleLoginButton.tsx
  src/components/domain/auth/hooks/useGoogleLogin.tsx
  src/components/domain/auth/index.tsx
  src/components/domain/expandableMenu/ChangeLanguage.tsx
  src/components/domain/expandableMenu/ExpandableMenu.tsx
  src/components/domain/expandableMenu/MenuContent.tsx
  src/components/domain/expandableMenu/index.tsx
  src/components/domain/influencer/OnePickInfluencer.tsx
  src/components/domain/influencer/index.tsx
  src/components/domain/mainAlarm/MainAlarm.tsx
  src/components/domain/mainAlarm/index.tsx
  src/components/domain/mainSearch/MainSearch.tsx
  src/components/domain/mainSearch/index.tsx
  src/components/domain/user/hooks/useInfluencerMode.tsx
  src/components/domain/user/hooks/useUserAvatar.tsx
  src/components/domain/user/index.ts
  src/components/domain/user/profile/MyProfileCard.tsx
  src/components/domain/user/profile/UserAvatar.tsx
  src/components/domain/user/setting/UserSettingsPanel.tsx
  src/components/features/header/index.ts
  src/components/features/influencer/index.ts
  src/components/features/user/index.ts
  src/components/layout/Header.tsx
Labels: ✨ feat, 🛠️ refactor

#31 📦 Chore/#30 회원가입 완료 페이지 다국어 처리
  messages/en.json
  messages/ko.json
  src/app/[locale]/(main)/my/edit/page.tsx
  src/components/domain/auth/DeleteAccountButton.tsx
  src/components/domain/auth/SignUpSuccess.tsx
  src/hooks/useInformationToast.tsx
Labels: 📦 chore

#38 ✨ Feat/#32 tailwind 컬러 추가, 타이포 설정 변경
  messages/ko.json
  src/app/[locale]/(main)/my/edit/page.tsx
  src/app/[locale]/(main)/my/page.tsx
  src/components/common/button/GoBackButton.tsx
  src/components/domain/auth/DeleteAccountButton.tsx
  src/components/domain/auth/GoogleLoginButton.tsx
  src/components/domain/auth/SignUpSuccess.tsx
  src/components/domain/auth/hooks/useGoogleLogin.tsx
  src/components/domain/influencer/OnePickInfluencer.tsx
  src/components/domain/user/profile/MyProfileCard.tsx
  src/components/domain/user/profile/UserAvatar.tsx
  src/components/domain/user/setting/UserSettingsPanel.tsx
  src/components/layout/BottomNavigation.tsx
  src/components/layout/Header.tsx
  src/components/ui/button.tsx
  tailwind.config.ts
Labels: ✨ feat

#40 ✨ Feat/#36 고객센터 스크린, 기능 작업
  messages/en.json
  messages/ko.json
  src/app/[locale]/(main)/my/customer-center/page.tsx
  src/constants/routes.ts
Labels: ✨ feat

#41 ✨ Feat/#37 메시지박스 공용 컴포넌트 추가
  src/components/common/modal/MessageBox.tsx
  src/lib/text.ts
Labels: ✨ feat

#43 ✨ Feat/#33 탭 공용 컴포넌트 추가
  package.json
  src/app/[locale]/(main)/page.tsx
  src/components/common/tab/SlideBarTabs.tsx
  src/components/ui/tabs.tsx
  yarn.lock
Labels: ✨ feat

#52 ✨ Feat/#34 유저 프로필 컴포넌트 추가, 활동내역 컴포넌트 분리
  messages/en.json
  messages/ko.json
  src/app/[locale]/(main)/my/activity-history/page.tsx
  src/app/[locale]/(main)/my/page.tsx
  src/app/[locale]/(main)/user/[userId]/_components/UserProfile.tsx
  src/app/[locale]/(main)/user/[userId]/page.tsx
  src/components/domain/influencer/OnePickInfluencer.tsx
  src/components/domain/user/activityHistory/CommentHistory.tsx
  src/components/domain/user/activityHistory/PostHistory.tsx
  src/components/domain/user/activityHistory/ReviewHistory.tsx
Labels: ✨ feat

#58 ✨ Feat/#54 인플루언서 상세 페이지 스크린 작업
  messages/en.json
  messages/ko.json
  src/app/[locale]/(main)/_components/PopularPost.tsx
  src/app/[locale]/(main)/_components/PopularReview.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/_components/BestReviewCard.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/_components/ContentTraits.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/_components/InfluencerProfileCard.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/_components/ReviewScoreCard.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/page.tsx
  src/app/[locale]/(main)/page.tsx
  src/app/[locale]/(main)/user/[userId]/_components/UserProfile.tsx
  src/app/[locale]/auth/login/page.tsx
  src/components/domain/board/BoardTypeTag.tsx
  src/components/domain/board/CommentCard.tsx
  src/components/domain/board/InteractionStats.tsx
  src/components/domain/board/TextPostCard.tsx
  src/components/domain/influencer/InfluencerReviewCard.tsx
  src/components/domain/influencer/InfluencerTagList.tsx
  src/components/domain/influencer/InfluencerThumbnail.tsx
  src/components/layout/Header.tsx
  src/components/ui/badge.tsx
  src/components/ui/button.tsx
  src/constants/routes.ts
  src/constants/testData.ts
  src/hooks/useCurrentRouteLabel.tsx
  src/lib/date.ts
  src/types/domain/boardType.ts
  src/types/domain/influencerType.ts
  src/types/domain/userType.ts
  tailwind.config.ts
Labels: ✨ feat

#51 ✨ Feat/#49 메인 메뉴 스크린 작업
  messages/en.json
  messages/ko.json
  src/components/screens/menu/ChangeLanguage.tsx
  src/components/screens/menu/MainSlideMenu.tsx
  src/components/screens/menu/MenuContent.tsx
  src/components/ui/sheet.tsx
  src/constants/routes.ts
  tailwind.config.ts
Labels: ✨ feat

#60 🐛 Fix/#59 메인메뉴 작업 수정, 빌드 오류 수정
  messages/en.json
  messages/ko.json
  src/app/[locale]/(main)/influencer/[influencerId]/page.tsx
  src/app/[locale]/auth/redirect/_hooks/useGoogleLogin.tsx
  src/components/domain/influencer/OnePickInfluencer.tsx
  src/components/screens/menu/ChangeLanguage.tsx
  src/components/screens/menu/MainSlideMenu.tsx
  src/components/screens/menu/MenuContent.tsx
  src/components/screens/signup/SignUpSuccess.tsx
  src/components/ui/button.tsx
  src/components/ui/sheet.tsx
  src/constants/routes.ts
  src/hooks/useCurrentRouteLabel.tsx
  src/types/domain/userType.ts
  src/types/service/authServiceType.ts
Labels: 🐛 fix

#62 ✨ Feat/#55 인플루언서 상세 페이지 한줄리뷰 crud 스크린 작업
  .eslintrc.json
  messages/en.json
  messages/ko.json
  package.json
  src/app/[locale]/(main)/influencer/[influencerId]/page.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/reviews/_components/MetricsText.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/reviews/_components/MyReview.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/reviews/_components/ReviewForm.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/reviews/_components/ReviewView.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/reviews/_components/ScoreSelectBox.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/reviews/_components/TextReviewCard.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/reviews/_hooks/useReviewForm.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/reviews/page.tsx
  src/components/common/MessageBox.tsx
  src/components/common/TooltipBox.tsx
  src/components/domain/user/activityHistory/CommentHistory.tsx
  src/components/domain/user/activityHistory/PostHistory.tsx
  src/components/domain/user/activityHistory/ReviewHistory.tsx
  src/components/ui/popover.tsx
  src/constants/routes.ts
  src/lib/text.ts
  src/types/domain/influencerType.ts
  tailwind.config.ts
  yarn.lock
Labels: ✨ feat

#69 ✨ Feat/#56 한줄리뷰 상세 페이지 스크린 작업
  messages/en.json
  messages/ko.json
  src/app/[locale]/(main)/community/[communityId]/[postId]/page.tsx
  src/app/[locale]/(main)/community/[communityId]/page.tsx
  src/app/[locale]/(main)/community/page.tsx
  src/app/[locale]/(main)/fan-channel/[communityId]/[postId]/page.tsx
  src/app/[locale]/(main)/fan-channel/[communityId]/page.tsx
  src/app/[locale]/(main)/fan-channel/page.tsx
  src/app/[locale]/(main)/follow/page.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/[reviewId]/page.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/_components/BestReviewCard.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/_components/ReviewScoreCard.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/page.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/review/[reviewId]/_components/CommentForm.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/review/[reviewId]/_components/LikeDislikeButtons.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/review/[reviewId]/_components/ReviewCommentList.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/review/[reviewId]/_components/ReviewDetailContent.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/review/[reviewId]/_hooks/useCommentForm.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/review/[reviewId]/_hooks/useLikeDislikeReview.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/review/[reviewId]/page.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/reviews/_components/ReviewForm.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/reviews/_components/ReviewView.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/reviews/_components/ScoreSelectBox.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/reviews/_components/TextReviewCard.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/reviews/_hooks/useReviewForm.tsx
  src/app/[locale]/(main)/influencer/[influencerId]/reviews/page.tsx
  src/app/[locale]/(main)/influencer/page.tsx
  src/app/[locale]/(main)/my/activity-history/page.tsx
  src/app/[locale]/(main)/my/customer-center/page.tsx
  src/app/[locale]/(main)/my/edit/page.tsx
  src/app/[locale]/(main)/my/page.tsx
  src/app/[locale]/(main)/page.tsx
  src/app/[locale]/(main)/user/[userId]/page.tsx
  src/components/common/MessageBox.tsx
  src/components/domain/influencer/FilledBarRating.tsx
  src/components/domain/influencer/MetricsText.tsx
  src/components/layout/Header.tsx
  src/components/layout/hooks/useBottomNavigationState.tsx
  src/constants/routes.ts
  src/hooks/useCurrentRouteLabel.tsx
  tailwind.config.ts
Labels: ✨ feat

#71 ✨ Feat/#67 drawer 컴포넌트 추가
  package.json
  src/components/common/ButtonListDrawer.tsx
  src/components/ui/drawer.tsx
  yarn.lock
Labels: ✨ feat

#72 ✨ Feat/#70 최상단 스크롤 버튼, 기능 추가
  src/app/[locale]/(main)/influencer/[influencerId]/_components/ReviewScoreCard.tsx
  src/components/layout/BottomNavigation.tsx
  src/components/layout/hooks/useMainScrollTop.tsx
Labels: ✨ feat
